### ISSUE TITLE
Домашнее задание №3

### ISSUE THREAD

**Issue by RybkaOlga** [viskvortsov/1C-developer#10]
Добрый вечер!
https://yadi.sk/d/P8iUc9ANxkuKK

**Comment by viskvortsov** [comment]
Сумма должна иметь возможность содержать копейки, как и цена.

Действительно ли нам нужно хранить остатки в разрезе издателей?

При делении нужно защищаться от того, что знаменатель может быть 0

По хорошему нужна проверка, что мы не выдаем больше 3 книг в руки.
