### ISSUE TITLE
ДЗ 1 Гусев

### ISSUE THREAD

**Issue by viskvortsov** [viskvortsov/1C-developer#110]
Расходного кассового ордера нет в интерфейсе
Форма приходного кассового ордер не открывается.
Надо поправить! )

**Comment by yalesorub** [comment]
[ДЦ1Юрий_V0.0001.zip](https://github.com/viskvortsov/1C-developer/files/1316711/1._V0.0001.zip)
Пофиксил,
1, Не добавил расходный в подсистему
2, Не правильно обозвал переменную в коде
