### ISSUE TITLE
ДЗ №2 Латынцев Игорь

### ISSUE THREAD

**Issue by IgorLatyncev** [viskvortsov/1C-developer#113]
[ДЗ №2 Латынцев Игорь 1С 8.3.10.2168.zip](https://github.com/viskvortsov/1C-developer/files/1327219/2.1.8.3.10.2168.zip)

**Comment by viskvortsov** [comment]
![1](https://user-images.githubusercontent.com/12106756/30791658-2ecdb1de-a1de-11e7-8544-af85786eef89.png)

![2](https://user-images.githubusercontent.com/12106756/30791664-31a356de-a1de-11e7-806e-9f70014754e5.png)

Не учтена возможность отсутствия строк в таблице.
А так хорошо.
5/5
