### ISSUE TITLE
ДЗ №3 Латынцев И.В.

### ISSUE THREAD

**Issue by IgorLatyncev** [viskvortsov/1C-developer#115]
[DZ3 Латынцев И.В. 8.3.10.zip](https://github.com/viskvortsov/1C-developer/files/1340815/DZ3.8.3.10.zip)

**Comment by viskvortsov** [comment]
Отлично!

Единственное замечание:
Расчет цены и запись номенклатуры лучше делать в одном серверном вызове, а не в двух.
