### ISSUE TITLE
ДЗ 2 Гребенников

### ISSUE THREAD

**Issue by Grant82** [viskvortsov/1C-developer#116]
[DZ2.zip](https://github.com/viskvortsov/1C-developer/files/1346435/DZ2.zip)

**Comment by viskvortsov** [comment]
4-/5

Замечания:
1. Не работает пересчет рублевой цены и суммы при изменении количество, цены или суммы в валюте;
2. При изменении цены или суммы в рублях выдается сообщение о недопустимости операции, но фактически запрета нет.

**Comment by Grant82** [comment]
Поправил
[ДЗ2.zip](https://github.com/viskvortsov/1C-developer/files/1384726/2.zip)
