### ISSUE TITLE
Боровых ДЗ 2

### ISSUE THREAD

**Issue by MikeBorovyh** [viskvortsov/1C-developer#117]
[Боровых_ДЗ№2.zip](https://github.com/viskvortsov/1C-developer/files/1346459/_.2.zip)

**Comment by viskvortsov** [comment]
4/5 

Некорректно организован пересчет данных при изменении в строке.
Например, при изменении суммы в валюте.
```
СтрТаб.ЦенаВРублях  = СтрТаб.ЦенаВВалюте  * Объект.КурсВалюты;
СтрТаб.СуммаВРублях = СтрТаб.СуммаВВалюте * Объект.КурсВалюты;
СтрТаб.ЦенаВВалюте  = СтрТаб.СуммаВВалюте /  СтрТаб.Количество;
```
Дело в том, что сначала нужно пересчитать цену в валюте, а потом от нее цену у рублях.
