### ISSUE TITLE
ДЗ №4 Латынцев И.В.

### ISSUE THREAD

**Issue by IgorLatyncev** [viskvortsov/1C-developer#127]
[ДЗ 4 Латынцев И.В. 8.3.10.zip](https://github.com/viskvortsov/1C-developer/files/1404389/4.8.3.10.zip)

**Comment by viskvortsov** [comment]
Замечания:
![risovach ru](https://user-images.githubusercontent.com/12106756/31858336-598d6238-b71f-11e7-8bb7-f42a8d368e49.jpg)

- Вместо непериодического РС с измерением "Дата" лучше сделать периодический регистр;
- Протягивать реквизит "наркотик" через документы и регистры совсем необязательно. Для этого достаточно просто галочки в карточке мед препарата. Опять же могут быть проблемы с закрытием регистра остатков;
- Ампула все-таки должна быть справочником, чтобы исключить ошибки ввода некорректных данных врачом.

А так очень даже хорошо.
Подбор порадовал.

Оценка:
5-/5
