### ISSUE TITLE
Домашняя работа 4, Иванов

### ISSUE THREAD

**Issue by alexsandro10** [viskvortsov/1C-developer#13]
https://cloud.mail.ru/public/9v82/ti97gwA1Y

**Comment by viskvortsov** [comment]
Это вычисляется как разница между датой открытия новой карточки и датой **первого проведения** документа

У вас и при простой записи без проведения будет вычисляться.

При выборе клиента в исходящем обращении все подставляется.
А вот при открытии уже записанного документа с клиентом нет.

Вместо

`ЭтотОбъект.ЭтаФорма.Телефон`
следует использовать просто:
`Телефон`
