### ISSUE TITLE
Ссылка

### ISSUE THREAD

**Issue by viskvortsov** [viskvortsov/1C-developer#14]
https://yadi.sk/d/PkurzZnzy6bbX

**Comment by alexsandro10** [comment]
Владимир, залейте, пожалуйста, внешний отчет, который мы на занятии выполняли, я его забыл забрать с собой:(

**Comment by viskvortsov** [comment]
Вот эти имеете в виду?
[Архив.zip](https://github.com/viskvortsov/1C-developer/files/581126/default.zip)

**Comment by alexsandro10** [comment]
Да, спасибо.
