### ISSUE TITLE
Домашнее задание 5

### ISSUE THREAD

**Issue by vladmirnik** [viskvortsov/1C-developer#15]
https://cloud.mail.ru/public/7EWR/oL5qj1PuG
сделал отчет по продажам
правильно ли я его сделал?
дальше пойду делать по деньгам

**Comment by viskvortsov** [comment]
Запрос сделан хорошо.

Но вот сам отчет составлен не правильно.
Вот что у меня получилось на выходе:
![2016-11-11_11-07-17](https://cloud.githubusercontent.com/assets/12106756/20204084/11e97262-a7ff-11e6-9feb-efd9a97b401f.png)

Ошибки: 
1. Сумма и средний чек должны быть ресурсами.
2. Нельзя задать дату начала и дату конца.
3. Сама компоновка выглядит странно: должно быть просто в строку: Клиент, сумма, средний чек. Таблица не нужна.

**Comment by viskvortsov** [comment]
Хотя подождите. С запросом я поторопился.
У вас не средний чек, а средняя цена выводится.
А нужен средний чек.
Он рассчитывается как Сумма / количество документов продажи.

**Comment by vladmirnik** [comment]
https://cloud.mail.ru/public/55gp/asfb4p3X3
Исправил первый отчет, проверил его вроде работает как надо
