### ISSUE TITLE
Домашняя работа №5, Иванов

### ISSUE THREAD

**Issue by alexsandro10** [viskvortsov/1C-developer#16]
Отчет №1
https://cloud.mail.ru/public/pRZs/8qEyZKyya

**Comment by alexsandro10** [comment]
Отчет №2
https://cloud.mail.ru/public/3SjK/nxMkQWyiy

**Comment by viskvortsov** [comment]
По отчету 1:
Количество продаж считается неправильно. Это не количество записей, а количество документов продажи. Один документ продажи может делать много записей, поэтому средний чек занижен.
Нет ресурсов у отчета, что при различных группировках может вызывать то, что не рассчитываются соответствующие показатели. Например вот так:
![2016-11-11_11-13-52](https://cloud.githubusercontent.com/assets/12106756/20204287/0e32e4d0-a801-11e6-8b9e-6324da7de65d.png)

**Comment by viskvortsov** [comment]
Отчет № 2: 
1. Полное соединение - это зло и оно здесь неоправдано. Нужно сделать без него.
2. Нет ресурсов (см. предыдущий комментарий).
3. Выборка в целом организована так, что обеспечивает задвоение данных (см. ниже).
3. Невозможно выбрать период, на какую дату посмотреть остатки.
4. Результат явно не сходится с фактом:
![2016-11-11_11-26-57](https://cloud.githubusercontent.com/assets/12106756/20204395/e7543232-a801-11e6-9f4e-c65c5fb34c1a.png)

**Comment by alexsandro10** [comment]
Исправил 2-ой отчет:
https://cloud.mail.ru/public/EXT6/yR27KiMfb

**Comment by alexsandro10** [comment]
В модуле объекта "Документ ПриходныйКассовыйОрдер" в процедуре ОбработкаПроведения пишем такой код:
	Если СуммаДокумента > 30000 И ХозяйственнаяОперация =    Перечисления.ХозяйственныеОперации.ПоступлениеОплатыОтКлиента Тогда
		Отказ = Истина;
		Сообщить("Слишком много нала! Спалимся!");
	КонецЕсли;
