### ISSUE TITLE
Вопрос по СКД

### ISSUE THREAD

**Issue by vladmirnik** [viskvortsov/1C-developer#19]
обещали курс по скд скинуть, говорили что вам еще не передавали его
актуально ли еще это?
я нашел бесплатный курс по СКД там 52 урока, он аналогичен то что хотели вы дать?

**Comment by viskvortsov** [comment]
Вот ссылка:
https://yadi.sk/d/5PbzHUQlzGSaq
Правда с его длительность я погорячился.
Перепутал его с другим курсом.
