### ISSUE TITLE
не  подходит версия  платформы

### ISSUE THREAD

**Issue by GirichS** [viskvortsov/1C-developer#27]
Добрый день, 
Григорий (группа2)
по  указанной  ссылке  на  скачивание  обучающей  версии 1с предприятие (http://online.1c.ru/catalog/free/18610119/)
версия  платформы 8,3,8,1933  она  отлична  от  той  которая  установлена в  учебном  классе  и требует обновиться до 8,3,9   где  можно  взять  бесплатное  обновление?

**Comment by viskvortsov** [comment]
Перезалил с использованием 8.3.8
Попробуйте еще раз.
