### ISSUE TITLE
Домашнее задание 1  Константин (группа 2)

### ISSUE THREAD

**Issue by kosta330** [viskvortsov/1C-developer#29]
Найти статью на http://infostart.ru/ Константин (группа 2)
http://infostart.ru/public/325478/

[1C-Russ Group2-v8.zip](https://github.com/viskvortsov/1C-developer/files/736805/1C-Russ.Group2-v8.zip)

В задании с плюсом не получилось Регистр накопления создать

**Comment by viskvortsov** [comment]
Замечания:
Списание безналичных денежных средств по своему смыслу должно уменьшать количество безналичных ДС, а не увеличивать.

В остальном - хорошо.
