### ISSUE TITLE
Домашка (проверка связи)

### ISSUE THREAD

**Issue by AVKharkova** [viskvortsov/1C-developer#30]
Владимир, пробую сдать на проверку задание. Но как?! ) К issues не крепится. Можно ссылкой?..
https://github.com/AVKharkova/1C-deposit/commit/6c765ce0b8a42f4a6731132f0cdb04faf5442691

**Comment by viskvortsov** [comment]
Как вариант.
Можно просто выкладывать на dropbox или yandex disk и давать ссылку.
Можно паковать в zip архив и кидать его сюда.

**Comment by viskvortsov** [comment]
Отлично!
