### ISSUE TITLE
ДЗ1Гулин

### ISSUE THREAD

**Issue by summernoise** [viskvortsov/1C-developer#32]
Добрый день.

Направляю выполненное домашнее задание.
Ссылка на статью:
http://infostart.ru/public/60705/
Ссылка на файл ДЗ:
https://www.dropbox.com/s/kvdxung0393cqqg/DR1.zip?dl=0

(прикрепляться сюда zip-архив почему-то отказался)

**Comment by viskvortsov** [comment]
Замечания:
ЗаказыКлиентов по идее все-таки накапливают заказы в различных разрезах, а значит скорее всего движение в регистр должно быть приходное, а не расходное.

В остальном хорошо.
