### ISSUE TITLE
Домашнее задание 2. Константин (группа 2)

### ISSUE THREAD

**Issue by kosta330** [viskvortsov/1C-developer#33]
Задание со звездочкой не получается. Не запомнил создание таблиц........
Где можно подглядеть?

[1C-Russ Group2-v8 _2.zip](https://github.com/viskvortsov/1C-developer/files/744200/1C-Russ.Group2-v8._2.zip)

**Comment by viskvortsov** [comment]
Например вот:
http://programmist1s.ru/registryi-svedeniy-1s/

**Comment by viskvortsov** [comment]
Вот есть информация:
https://helpf.pro/faq/cat/18.html

**Comment by kosta330** [comment]
Создал регистр сведений из задания со звездочкой......Правильно ли я уловил смысл задания? 
[1C-Russ Group2-v8 _2.zip](https://github.com/viskvortsov/1C-developer/files/752055/1C-Russ.Group2-v8._2.zip)

**Comment by viskvortsov** [comment]
Два момента:

1. Регистр "Заказы поставщикам" должен отвечать на вопрос "Сколько товара и на какой склад заказано?"
Невозможно ответить на этот вопрос, если при поступлении товара на склад мы не уменьшаем количество заказанного. Тоесть должно быть расходное движение по регистру при поступлении товара.

2. Что касается регистра. Ключевой момент задания вот:
`Должна быть возможность указать какого числа придет каждая строка заказа поставщику. `
Тоесть возможность указать на какую дату придет товар должна быть для каждой строки заказа.
И движение должен делать заказ, а не поступление.
