### ISSUE TITLE
02. Домашнее задание (группа № 2) Харькова

### ISSUE THREAD

**Issue by AVKharkova** [viskvortsov/1C-developer#34]
Ссылка на файл конфигурации: https://yadi.sk/d/NGT0FYrh3CoAZK
У меня в голове даты плохо монтируются с регистром сведений, не понятно, как их там уложить, как использовать. Ну, как поняла, так и сделала )

**Comment by viskvortsov** [comment]
С регистром сведений почти все правильно. Единственное - нет информации о том, сколько придет товаров. А это может быть очень важно. По хорошему нужно сделать еще ресурс количество и записывать информацию туда.

Регистр "Заказы поставщикам" должен отвечать на вопрос "Сколько товара и на какой склад заказано?"
Невозможно ответить на этот вопрос, если при поступлении товара на склад мы не уменьшаем количество заказанного. Тоесть должно быть расходное движение по регистру при поступлении товара.
