### ISSUE TITLE
Контрольная работа 1(Гулин)

### ISSUE THREAD

**Issue by summernoise** [viskvortsov/1C-developer#39]
Направляю файл первой контрольной работы.

**Comment by summernoise** [comment]
Попытка номер два

**Comment by summernoise** [comment]
Попытка номер три.
[KR1.zip](https://github.com/viskvortsov/1C-developer/files/785494/KR1.zip)

**Comment by viskvortsov** [comment]
Проверки заполненности лучше осуществлять в процедуре ПриЗаписи, чем в ОбработкеПроведения.
В расходе денежных средств синтаксическая ошибка в запросе.

В остальном хорошо.
Оценка: 5-/5
