### ISSUE TITLE
Исаев ДЗ № 2

### ISSUE THREAD

**Issue by Incvisitor** [viskvortsov/1C-developer#70]
Ссылка: https://yadi.sk/d/RscrrOe13GvVtS

Вот вопросы возникшие в процессе выполнения:
1.	Можно ли завести на отдельного поставщика отдельный справочки (допустим товаров) программно?
2.	Можно ли щелкнув в нужном меню у свойства элемента формы, найти на него ссылки в коде?
3.	К чему может привести отсутствие закрывающих ; ? (Просто иногда программа может скомпилироваться и не выдать ошибку, если этот оператор стоит непосредственно перед концом функции/процедуры)

**Comment by viskvortsov** [comment]
В процедуре ПоставщикПриИзменении(Элемент); происходит вызов сервера в цикле, что даст деградацию производительности при большом количестве строк.

Лучше делать валюту справочником. 
Вдруг компания будет торговать с Китаем? 

В остальном хорошо.
5-/5
