### ISSUE TITLE
Исаев ДЗ №3

### ISSUE THREAD

**Issue by Incvisitor** [viskvortsov/1C-developer#74]
https://yadi.sk/d/BgBbBx_h3HEnEQ

В общем, что-то у меня как-то кривенько вышло (я так думаю).

Есть несколько защит от беспросветно глупых действий, но возможно сломать есть возможность.
Очень не понравилось то, как реализовал запросы - хочется детальнее остановиться на них.

Возник ряд вопросов:
1. Как мне передать целую таблицу непосредственно в запрос? Я лепил ее из ТаблицыЗначений, потом засовывал ее как Параметр (временная таблица) в Запрос, но он всегда ругался на какие-то проблемы с типами и прочей ерундой. Хочется узнать, это можно реализовать грамотно.
2. Можно ли отправить во временную таблицу запроса непосредственно элемент? Например отправить туда весь справочник программно? А то опять же, конфликт с типами, непонятно.
3. Как можно контролировать удаление из регистра сведений? Некоторые параметры на основании его пересчитываются, но такой функции как ПослеУдаления я не обнаружил. Как проверять изменяемость объекта?

**Comment by viskvortsov** [comment]
Хорошее решение.

У нас
`ИСТИНА`
пишется как
`Истина`

Статус работы лучше сделать перечислением.

Если успеваемость рассчитывается при создании формы на сервере, от нет смысла ее считать и записывать в студента в документе.
Вопросы разберем на занятии.

5/5
