### ISSUE TITLE
Работа по заданию Книг

### ISSUE THREAD

**Issue by vladmirnik** [viskvortsov/1C-developer#8]
Приветстсвую,
Заводил Регистр накопления По остаткам книг,
в коде по проведению документа застопорился на количестве книг
чтобы для определенной книги при изменении кол-во увеличивалось
задал цикл
Строка.Количество = 0
для каждого строка из УчетКниг Цикл

Строка.Количество = Строка.количество + УчетКниг. Количество
продолжить
КонецЦикла;

проставил "продолжить" чтобы строки фиксировались по наименованию
это получилось.
кол-во  меняется при перепроведении как записалось в документе ПриходКниг.
а должно учитываться прошлое значение кол-во книг,
тут нужно ли отрабатывать запрос "Выборка.СрезПоследних" чтоб потом прибавить тек.значение?

**Comment by viskvortsov** [comment]
Что такое УчетКниг?
Что содержится в этой переменной?

**Comment by viskvortsov** [comment]
Киньте скриншот модуля или текст модуля, так как не зная контекста тяжело ответить на вопрос

**Comment by vladmirnik** [comment]
вот ссылка
https://cloud.mail.ru/public/BrGy/Y4B78bpDP
сегодня еще дорабатывать буду по отчетам

**Comment by vladmirnik** [comment]
Документ Регистрация книг, в нем код по проведению

**Comment by viskvortsov** [comment]
1. Непонятно для чего реквизит количество в справочнике Книги.
Создается впечатление, что он не нужен.

2. Есть явная проблема с логикой в документе РегистрацияКниг
Есть книга в шапке документа и книга в таблице. При этом движения делаются в регистр по реквизиту из шапки, суммирую количество в строках документа, что создает парадокс:
Выбрали книгу "Анна Каренина" в шапке, затем в первой строке:
"Идиот" 2 шт
"Горе от ума" - 3 шт
А в регистр ОстаткиКниг записалось "Анна Каренина" - 5 шт.

3. В документе РегистрацияКниг в ТЧ реквизит Количество строкового типа, а должен быть числом.

4. В цикле:
```
Для Каждого Строка Из УчетКниг Цикл		
		
	КоличествоДокумента = КоличествоДокумента + Строка.Количество;		
	продолжить;

КонецЦикла;
```
Ключевое слово Продолжить не нужно, так как цикла сам продолжается, когда доходит до КонецЦикла.

5. Не ясно для чего получать количество книг из справочника Книги в форме документа РегистрацияКниг:
```
&НаКлиенте
Процедура УчетКнигНазваниеПриИзменении(Элемент)
	// Вставить содержимое обработчика.
	ТекущиеДанные = Элементы.УчетКниг.ТекущиеДанные;
	
	ТекущиеДанные.Количество = ПолучитьКоличествоКниг(ТекущиеДанные.Название);
	
КонецПроцедуры

&НаСервере
Функция ПолучитьКоличествоКниг()
	
	возврат Название.Количество;
	
КонецФункции

```
