### ISSUE TITLE
Домашняя3_Иванов

### ISSUE THREAD

**Issue by alexsandro10** [viskvortsov/1C-developer#9]
https://cloud.mail.ru/public/8XHQ/4mzfot2Mb

**Comment by viskvortsov** [comment]
Год издания должен быть датой, либо должно проверяться, что пользователь не ввел там что-нибудь типа "йцук"

Расчет реквизита "СуммаПоЗакупке" документа ЗакупкаКниг должен производится в событии ПередЗаписью.

Расчет реквизита "СуммаПоЗакупке" документа ВыдачаКниг должен производится в событии ПередЗаписью.
