### ISSUE TITLE
Исаев ДЗ №4

### ISSUE THREAD

**Issue by Incvisitor** [viskvortsov/1C-developer#90]
https://yadi.sk/d/j1Kubb-K3JLDbN

Вопросы:

1.	Как пользоваться глобальными константами?
2.	Можно ли пользоваться глобальными константами в запросах напрямую или их нужно сообщать?
3.	Почему при сборке в списке сборок не выводится Текущая Версия, хотя она везде указывается, регистрируется и даже в регистре накопления отображается?

Про задание: как-то так. Из баго-фич:
1. Можно перепроводить данную конфигурацию в любое время, если она одна.
2. Можно создавать "в прошло" конфигурации менее чем через 7 дней, но вперед нельзя.
3. Можно напродавать блоков с одной конфигурацией, затем ее изменить, но в регистрах накопления и сборках информация не изменится, так что логично было бы заблокировать изменение конфигураций (но тут уже на вкус и цвет, я не стал блокировать, но сделать это легко (как мне кажется)).

**Comment by viskvortsov** [comment]
Замечания:

- Продавать мы должны по какой-то цене, а не по себестоимости, иначе на чем мы будем зарабатывать?
- Валовая прибыль - разница между выручкой и себестоимостью реализованной продукции или услуги. Тоесть в отчете должна отражаться только та часть себестоимости, которая относится к проданному товару.

В целом, хорошо.
Оценка: 5-/5

**Comment by Incvisitor** [comment]
С валовой прибылью да, я ошибся.
А себестоимость там считается теневыми схемами. Когда блок заносится в базу, при сборке, его цена умножается на 1,25. Таким образом с продажи у нас 0,25 прибыли.
